const api = require("lambda-api")()
const ada1 = require("./src/routes/ada-1.js")
const authorize = require("./src/routes/authorize.js")
const banshee44 = require("./src/routes/banshee-44.js")
const commanderZavala = require("./src/routes/commander-zavala.js")
const devrimKay = require("./src/routes/devrim-kay.js")
const failsafe = require("./src/routes/failsafe.js")
const init = require("./src/routes/init.js")
const lordShaxx = require("./src/routes/lord-shaxx.js")
const modDataForLastYear = require("./src/routes/mod-data-for-last-year.js")
const theDrifter = require("./src/routes/the-drifter.js")
const xur = require("./src/routes/xur.js")

api.register(ada1)
api.register(authorize)
api.register(banshee44)
api.register(commanderZavala)
api.register(devrimKay)
api.register(failsafe)
api.register(init)
api.register(lordShaxx)
api.register(modDataForLastYear)
api.register(theDrifter)
api.register(xur)

exports.handler = async (event, context) => {
  return api.run(event, context)
}
